[package]
  cjc-version = "1.0.0"
  name = "spire_web_cors"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "static"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
  spire_web_http = { path = "../spire_web_http"}
  spire_web_routing = { path = "../spire_web_routing"} 
  spire_extensions_options = { path = "../spire_extensions_options"} 
  spire_extensions_logging = { path = "../spire_extensions_logging"} 
  spire_extensions_injection = { path = "../spire_extensions_injection"} 

[target]
  [target.x86_64-w64-mingw32]
    compile-option = "-Woff unused --diagnostic-format=noColor -Woff deprecated -lcrypt32"
    [target.x86_64-w64-mingw32.bin-dependencies]
      path-option = [ "${CANGJIE_STDX_PATH}" ]
  [target.x86_64-unknown-linux-gnu]
    compile-option = "-Woff unused --diagnostic-format=noColor -Woff deprecated -ldl"
    [target.x86_64-unknown-linux-gnu.bin-dependencies]
      path-option = [ "${CANGJIE_STDX_PATH}" ]
  [target.aarch64-unknown-linux-gnu]
    compile-option = "-Woff unused --diagnostic-format=noColor -Woff deprecated -ldl"
    [target.aarch64-unknown-linux-gnu.bin-dependencies]
      path-option = [ "${CANGJIE_STDX_PATH}" ]