
[package]
  cjc-version = "1.0.0"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "spire_web_routing"
  output-type = "static"
  override-compile-option = ""
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}

[dependencies]
  spire_web_http = { path = "../spire_web_http"}
  spire_extensions_options = { path = "../spire_extensions_options"}
  spire_extensions_injection = { path = "../spire_extensions_injection"}  
