[package]
  cjc-version = "1.0.1"
  name = "spire_extensions_http"
  description = "nothing here"
  version = "1.0.1"
  target-dir = ""
  src-dir = ""
  output-type = "static"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
  spire_net_http = { path = "../spire_net_http"}
  spire_extensions_options = { path = "../spire_extensions_options"}  
  spire_extensions_injection = { path = "../spire_extensions_injection"}  