[package]
  cjc-version = "1.0.1"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "spire_unnitests"
  output-type = "static"
  override-compile-option = ""
  src-dir = "src"
  target-dir = ""
  version = "1.0.1"
  package-configuration = {}

[dependencies]
  spire_extensions_injection = { path = "../spire_extensions_injection" }
  spire_extensions_configuration = { path = "../spire_extensions_configuration" }
  spire_extensions_caching = { path = "../spire_extensions_caching" }
  spire_extensions_options = { path = "../spire_extensions_options" }
  spire_extensions_logging = { path = "../spire_extensions_logging" }

[target]
  [target.x86_64-w64-mingw32]
    compile-option = "-Woff unused --diagnostic-format=noColor -Woff deprecated -lcrypt32"
    [target.x86_64-w64-mingw32.bin-dependencies]
      path-option = [ "${CANGJIE_STDX_PATH}" ]
  [target.x86_64-unknown-linux-gnu]
    compile-option = "-Woff unused --diagnostic-format=noColor -Woff deprecated -ldl"
    [target.x86_64-unknown-linux-gnu.bin-dependencies]
      path-option = [ "${CANGJIE_STDX_PATH}" ]
  [target.aarch64-unknown-linux-gnu]
    compile-option = "-Woff unused --diagnostic-format=noColor -Woff deprecated -ldl"
    [target.aarch64-unknown-linux-gnu.bin-dependencies]
      path-option = [ "${CANGJIE_STDX_PATH}" ]
