
[package]
  cjc-version = "1.0.0"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "spire_web_hosting"
  output-type = "static"
  override-compile-option = ""
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}

[dependencies]
  spire_web_http = { path = "../spire_web_http"}
  spire_identity_claims = { path = "../spire_identity_claims"}
  spire_extensions_hosting = { path = "../spire_extensions_hosting"}
  spire_extensions_logging = { path = "../spire_extensions_logging"}
  spire_extensions_options = { path = "../spire_extensions_options"}
  spire_extensions_injection = { path = "../spire_extensions_injection"}
  spire_extensions_configuration = { path = "../spire_extensions_configuration"}
  spire_extensions_logging_configuration = { path = "../spire_extensions_logging_configuration"}

[target]
  [target.x86_64-w64-mingw32]
    compile-option = "-Woff unused --diagnostic-format=noColor -Woff deprecated -lcrypt32"
    [target.x86_64-w64-mingw32.bin-dependencies]
      path-option = [ "${CANGJIE_STDX_PATH}" ]
  [target.x86_64-unknown-linux-gnu]
    compile-option = "-Woff unused --diagnostic-format=noColor -Woff deprecated -ldl"
    [target.x86_64-unknown-linux-gnu.bin-dependencies]
      path-option = [ "${CANGJIE_STDX_PATH}" ]
  [target.aarch64-unknown-linux-gnu]
    compile-option = "-Woff unused --diagnostic-format=noColor -Woff deprecated -ldl"
    [target.aarch64-unknown-linux-gnu.bin-dependencies]
      path-option = [ "${CANGJIE_STDX_PATH}" ]